In [1]:
import os

if not os.path.exists('thinkdsp.py'):
    !wget https://github.com/AllenDowney/ThinkDSP/raw/master/code/thinkdsp.py

In [2]:
import matplotlib.pyplot as plt

from thinkdsp import CosSignal
from thinkdsp import decorate
from thinkdsp import Chirp

In [3]:
import numpy as np
π = 3.1415926
def myDFT(x):
    N = len(x)
    n = np.arange(N)
    k = np.arange(N)
    kn = np.outer(k,n)
    M = np.exp(-1j * 2 * π * kn)
    X = M.dot(x)
    return X

In [4]:
np.set_printoptions(precision=3)
x = np.array([1, 1, 1, 1])
X = myDFT(x)
print(X)

[4.+0.000e+00j 4.+6.431e-07j 4.+1.286e-06j 4.+1.929e-06j]


In [87]:
import numpy.fft as fft
X = fft.fft(x)
print(X)

[4.+0.j 0.+0.j 0.+0.j 0.+0.j]


In [19]:
X1 = myDFT(x)
X2 = fft.fft(x)
diff = np.subtract(X1,X2)
square = np.square(diff)
MSE = square.mean()
RMSE = np.sqrt(MSE)
print(RMSE)

(3.4641016151373996+1.1138429318877143e-06j)


In [108]:
x = [1,2,3,4,5,6,7,8]
y = [1,1,1,1]

In [132]:
def myCONV(x,y):
    y = np.append(y,[0]*(len(x)-1)) # zero padding
    m = np.arange(len(y))
    zL = []
    for n in range(len(y)):
        z = x[len(x)-1-n] * y[n] 
        zL +=[z]
    zL = np.array(zL)
    return zL
myCONV(x,y)

array([8, 7, 6, 5, 0, 0, 0, 0, 0, 0, 0])

In [101]:
def myCONV2(x,y):
    x = np.array(x)
    y = np.append(y,[0]*(len(x)-1)) # zero padding
    m = np.array(len(x)).reshape(1,-1) #row vector
    n = np.array(len(y)).reshape(-1,1) #column vector
    z = np.convolve(x,y)
    return z
myCONV2(x,y)

array([ 1,  3,  6, 10, 14, 18, 22, 26, 21, 15,  8,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0])

In [100]:
z = np.convolve(x,y)
print(z)

[ 1  3  6 10 14 18 22 26 21 15  8  0  0  0  0]


In [88]:
import numpy as np
π = 3.1415926
np.set_printoptions(0)
x = np.array([1,1,1,1])
def myDFT(x):
    N = len(x)
    n = np.arange(N)
    k = np.arange(N)
    kn = np.outer(k,n)
    M = np.exp(-1j * 2 * π * kn/N)
    X = M.dot(x)
    return X
X = myDFT(x)
print(X)

[ 4.e+00+0.e+00j -5.e-08-5.e-08j  8.e-15-1.e-07j  2.e-07-2.e-07j]


In [90]:
x = [1,2,3,4,5,6,7,8]
y = [1,1,1,1]
z = np.convolve(x,y)
print(len(x))
print(len(y))
print(len(z))

8
4
11
